### ISSUE TITLE
Ver. 1.4.0 NoSuchMethodError: com.google.cloud.datastore.DatastoreOptions$Builder.setConnectTimeout

### ISSUE THREAD

**Issue by MuBoori** [sai-pullabhotla/catatumbo#129] opened 2017-04-19 19:00 UTC
I tried to ver 1.4.0 latest version in Maven but I get the below error but when I downgraded to 1.3.1 the library works fine

```
java.lang.NoSuchMethodError: com.google.cloud.datastore.DatastoreOptions$Builder.setConnectTimeout(I)Lcom/google/cloud/HttpServiceOptions$Builder;
     com.jmethods.catatumbo.EntityManagerFactory.createEntityManager(EntityManagerFactory.java:265)
     com.jmethods.catatumbo.EntityManagerFactory.createEntityManager(EntityManagerFactory.java:187)
     com.jmethods.catatumbo.EntityManagerFactory.createEntityManager(EntityManagerFactory.java:162)
     com.jmethods.catatumbo.EntityManagerFactory.createEntityManager(EntityManagerFactory.java:142)
     com.jmethods.catatumbo.EntityManagerFactory.createEntityManager(EntityManagerFactory.java:92)
```

**Comment by sai-pullabhotla** [comment] 2017-04-19 22:50
@MuBoori  - I'm unable to reproduce this issue. My Maven POM has the following dependency and was able to interact with the Datastore without any issues. My guess is that your Runtime Class Path has an incompatible version of Google Cloud Java API, than what Catatumbo 1.4.0 requires. Catatumbo 1.4.0 requires 0.9.4-beta version of Google Cloud Java API. Newer versions of the Google Cloud API have a breaking change (not backward compatible) for setting the timeouts. 

Please double check your runtime class path and try again. 

```
    <dependency>
      <groupId>com.jmethods</groupId>
      <artifactId>catatumbo</artifactId>
      <version>1.4.0</version>
    </dependency>

```

**Comment by MuBoori** [comment] 2017-04-19 22:54
I'm using Google Cloud Datastore  v. 0.13.0-beta
I've not tried to downgrade my google cloud datastore api but catatumbo v1.3.1 and older works fine.

**Comment by sai-pullabhotla** [comment] 2017-04-19 23:53
That explains it. Newer versions of Google Cloud Java API use TransportOptions to set the timeouts. The reason why Catatumbo 1.3.1 works is because versions prior to 1.4.0 did not attempt to set any timeouts and left it up to the Google Cloud Java API to use the defaults. So, the timeout methods are never called explicitly. Anyhow, I recommend using the compatible versions of Catatumbo and Google Cloud Java. I will be releasing a new version soon, hopefully this weekend, that will use the latest Google Cloud Java API.

**Comment by sai-pullabhotla** [comment] 2017-04-24 18:44
Not an issue, closing this.

**Closed as completed by sai-pullabhotla** 2017-04-24 18:44 UTC
