### ISSUE TITLE
Support arrays on namedBindings

### ISSUE THREAD

**Issue by andre2k2** [sai-pullabhotla/catatumbo#98] opened 2017-01-23 17:57 UTC
Once that GqlQuery.Builder accepts varargs on setBinding method, it's nice to support varargs or arrays on QueryUtils.applyNamedBindings(..).

**Comment by sai-pullabhotla** [comment] 2017-01-24 18:45
@andre2k2, Would you please elaborate on what your requirement is? QueryUtils is an internal class, but if you need any changes related to this, it would have to be done in QueryRequest. If you could provide your use case, I will look into this.

**Comment by sai-pullabhotla** [comment] 2017-02-28 01:51
Closing this due to lack of clarification and possibly a duplicate of #108.

**Closed as completed by sai-pullabhotla** 2017-02-28 01:51 UTC
